export const ECONOMY = {
  CURRENCY: "$",
  CURRENCY_SIGN: "€",
  LESSONS_PRICE: 100,
  LESSONS_PROFIT: 150,
  AVERAGE_LESSON_DURATION: 180,
  LOSS_PER_EXTRA_SECONDS: 1,
  MAX_USER_LIVES: 6,
  MAX_USER_STREAK_SHIELDS: 3,
  LIFE_REGENERATION_TIME_HOURS: 3,
};
